### ISSUE TITLE
typst v0.11.0 でのビルド

### ISSUE THREAD

**Issue by derwind** [arakur/typst-to-mathlog#1]
突然で失礼いたします。Zenn の記事を拝見して大変興味深く素晴らしいアプリケーションだと思い触らせていただきました。最新の typst で使いたいと思いビルドを試みましたが、単純に typst v0.11.0 のクレートを使うだけではビルドエラーに至りました。

Rust は詳しくないので調べながらの対応になったのですが、typst 側の API 変更に追従する形で
[diff.patch.txt](https://github.com/arakur/typst-to-mathlog/files/14960505/diff.patch.txt)
のような内容で、typst v0.11.0 で動作することを確認いたしました (自分で書いた記事の変換が通ることで確認しました)。不備もあるかもしれませんが、その場合は申し訳ございません。

もし公式に最新の typst へのご対応のご予定があるのであればそれが一番良いと思います。

**補足**

- 正確には私は WSL2 環境で動かしたので、`main.rs` にも手を入れて Windows のパスと Linux のパスを扱えるようにしました。このパス変換は本質ではないので上記のパッチには含めていません。
- また、個人的に使いたいシンボルが幾つかありましたので、`dictionary_patch.json` に追加をして `make_dictionary.py` で `dictionary_patch.json` の更新もしましたが、これは個人の好みの部分になりますのでやはりパッチには含めていません。

**ビルド環境**

- WSL2 Ubuntu 20.04
- rustc 1.77.1 (7cf61ebde 2024-03-27)

**Comment by arakur** [comment]
ご報告ありがとうございます．ビルドエラーとパッチの内容のほう確認いたしました．
修正については確認した限り問題なさそうです．`typst` のインポートでのバージョン指定漏れもありお手数をおかけしてしまったと思います，ありがとうございました．
こちらの内容で更新しようと思いますが，コントリビュータが明示されたほうがよいと思いますので，よろしければそちらでプルリクエストのほうを作成していただけますでしょうか．

**Comment by derwind** [comment]
@arakur 承知しました。PR を作成いたします。
